### ISSUE TITLE
init takes a param

### ISSUE THREAD

**Issue by brianleroux** [architect/create#1]
`arc init foobar` should create a directory named foobar with `.arc` file app named 'foobar' in it. this changed at some point and no longer works.

**Comment by ryanblock** [comment]
Create now fixes the runtime param (`runtime`, `--runtime`, or `-r` + `node`, `js`, `python`, `py`, `ruby`, `rb`) and accepts a final param as either an app name, or app name + app dir. Examples:

```
create ......... creates project named for current dir in current dir
create ./ ...... creates project named for current dir in current dir
create foo ..... creates project named foo in current dir
create ./foo ... creates ./foo dir, creates project named foo that dir
create ../foo .. creates ../foo dir, creates project named foo that dir
create /foo .... creates /foo dir, creates project named foo that dir
create ../ ..... creates project named for .. dir name in .. dir
```
