### ISSUE TITLE
WS functions all created with the name `subscribe`

### ISSUE THREAD

**Issue by andybee** [architect/create#2]
**Describe the issue**
On discovery of `@ws` pragma in `.arc`, `arc init` creates the WS functions using the templates in `@architect/utils`. Because it repeats the one-to-one style for Lambda functions, there is a single template for the 3x required functions for Web Sockets via API Gateway. As a  result, the initial functions for each WS function is called `subscribe`.

**Steps to reproduce**
1. Create a new project and add `@ws` pragma to `.arc`.
2. Run `arc init`.
3. Observe the `src/ws/*/index.js` files.

**Expected behavior**
The generated function names would reflect their purpose (e.g. `subscribe`, `message`, `unsubscribe`).

**Comment by ryanblock** [comment]
We've gone back and forth on this, and are now trying to keep things as minimal as possible for the time being.

Anyway, fix for this issue coming in a few!
